# Generated by Django 3.2.8 on 2022-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
